import{S as l,i as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const u="44900645-90bb6bb627b06b4b3923afb1e",f="https://pixabay.com/api/";async function d(n){const r=await fetch(`${f}?key=${u}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`);if(!r.ok)throw new Error("Network response was not ok");return await r.json()}const p=new l(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,close:!0,showCounter:!0,enableKeyboard:!0});function m(n){const r=document.querySelector(".gallery");r.innerHTML=n.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item">
            <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
            <div class="info">
                <p class="info-item"><b>Likes</b>: ${t.likes}</p>
                <p class="info-item"><b>Views</b>: ${t.views}</p>
                <p class="info-item"><b>Comments</b>: ${t.comments}</p>
                <p class="info-item"><b>Downloads</b>: ${t.downloads}</p>
            </div>
        </a>
    `).join(""),p.refresh()}function y(){const n=document.querySelector(".gallery");n.innerHTML=""}function a(n){c.error({title:"Error",message:n})}function h(){document.querySelector(".loader-wrapper").style.display="flex"}function g(){document.querySelector(".loader-wrapper").style.display="none"}document.getElementById("search-form").addEventListener("submit",function(n){n.preventDefault();const r=document.getElementById("search-input").value.trim();if(r===""){iziToast.warning({title:"Warning",message:"Please enter a search query"});return}document.getElementById("search-input").value="",h(),y(),d(r).then(t=>{t.hits.length===0?a("Sorry, there are no images matching your search query. Please try again!"):m(t.hits)}).catch(t=>{a("An error occurred while fetching images. Please try again later.")}).finally(()=>{g()})});
//# sourceMappingURL=commonHelpers.js.map
