import{S as c,i as l}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const u="44900645-90bb6bb627b06b4b3923afb1e",d="https://pixabay.com/api/";async function f(n){const o=await fetch(`${d}?key=${u}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`);if(!o.ok)throw new Error("Network response was not ok");return await o.json()}function m(n){const o=document.querySelector(".gallery");o.innerHTML=n.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            <div class="info">
                <p class="info-item"><b>Likes</b>: ${r.likes}</p>
                <p class="info-item"><b>Views</b>: ${r.views}</p>
                <p class="info-item"><b>Comments</b>: ${r.comments}</p>
                <p class="info-item"><b>Downloads</b>: ${r.downloads}</p>
            </div>
        </a>
    `).join("");const s=new c(".gallery a",{});s.on("shown.simplelightbox",function(){const e=document.querySelector(".sl-image img").alt,t=document.createElement("div");t.classList.add("alt-text"),t.textContent=e,document.querySelector(".sl-wrapper").appendChild(t)}),s.on("close.simplelightbox",function(){const r=document.querySelector(".alt-text");r&&r.remove()})}function a(n){l.error({title:"Error",message:n})}function p(){document.querySelector(".loader-wrapper").style.display="flex"}function y(){document.querySelector(".loader-wrapper").style.display="none"}document.getElementById("search-form").addEventListener("submit",async n=>{n.preventDefault();const o=document.getElementById("search-input").value.trim();if(o===""){iziToast.warning({title:"Warning",message:"Please enter a search query"});return}p();try{const s=await f(o);s.hits.length===0?a("Sorry, there are no images matching your search query. Please try again!"):m(s.hits)}catch{a("An error occurred while fetching images. Please try again later.")}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
